theme: jekyll-theme-dinky
title: <a href="https://field-matters.github.io/">Field matters</a>
description: The first workshop on NLP applications to field linguistics </br></br><a style="font-weight:bold"; href="https://field-matters.github.io/cfp">Call for papers</a></br><a style="font-weight:bold" href="https://field-matters.github.io/sharedtask">Shared tasks</a>
github:
  is_project_page: false

